//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrolmentForm2.CourseAdminServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/EnrolmentAdminService")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((this.CourseIDField.Equals(value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CourseAdminServiceReference.ICourseAdmin")]
    public interface ICourseAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseAdmin/NewCourse", ReplyAction="http://tempuri.org/ICourseAdmin/NewCourseResponse")]
        void NewCourse(int CourseID, string CourseName, decimal Cost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseAdmin/NewCourse", ReplyAction="http://tempuri.org/ICourseAdmin/NewCourseResponse")]
        System.Threading.Tasks.Task NewCourseAsync(int CourseID, string CourseName, decimal Cost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseAdmin/ViewCourse", ReplyAction="http://tempuri.org/ICourseAdmin/ViewCourseResponse")]
        EnrolmentForm2.CourseAdminServiceReference.Course[] ViewCourse();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseAdmin/ViewCourse", ReplyAction="http://tempuri.org/ICourseAdmin/ViewCourseResponse")]
        System.Threading.Tasks.Task<EnrolmentForm2.CourseAdminServiceReference.Course[]> ViewCourseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseAdmin/DisplayBill", ReplyAction="http://tempuri.org/ICourseAdmin/DisplayBillResponse")]
        EnrolmentForm2.CourseAdminServiceReference.Course[] DisplayBill();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseAdmin/DisplayBill", ReplyAction="http://tempuri.org/ICourseAdmin/DisplayBillResponse")]
        System.Threading.Tasks.Task<EnrolmentForm2.CourseAdminServiceReference.Course[]> DisplayBillAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICourseAdminChannel : EnrolmentForm2.CourseAdminServiceReference.ICourseAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseAdminClient : System.ServiceModel.ClientBase<EnrolmentForm2.CourseAdminServiceReference.ICourseAdmin>, EnrolmentForm2.CourseAdminServiceReference.ICourseAdmin {
        
        public CourseAdminClient() {
        }
        
        public CourseAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NewCourse(int CourseID, string CourseName, decimal Cost) {
            base.Channel.NewCourse(CourseID, CourseName, Cost);
        }
        
        public System.Threading.Tasks.Task NewCourseAsync(int CourseID, string CourseName, decimal Cost) {
            return base.Channel.NewCourseAsync(CourseID, CourseName, Cost);
        }
        
        public EnrolmentForm2.CourseAdminServiceReference.Course[] ViewCourse() {
            return base.Channel.ViewCourse();
        }
        
        public System.Threading.Tasks.Task<EnrolmentForm2.CourseAdminServiceReference.Course[]> ViewCourseAsync() {
            return base.Channel.ViewCourseAsync();
        }
        
        public EnrolmentForm2.CourseAdminServiceReference.Course[] DisplayBill() {
            return base.Channel.DisplayBill();
        }
        
        public System.Threading.Tasks.Task<EnrolmentForm2.CourseAdminServiceReference.Course[]> DisplayBillAsync() {
            return base.Channel.DisplayBillAsync();
        }
    }
}
